### ISSUE TITLE
console shows Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-editor#82] opened 2015-06-04 09:19 UTC
Seems to occur for any and all sketches.

![screenshot 2015-06-04 10 18 52](https://cloud.githubusercontent.com/assets/191758/7980901/2e69fac4-0aa3-11e5-9a9b-db271572b86a.png)

**Comment by antiboredom** [comment] 2015-06-04 14:22
closing this as it is a duplicate of #69

**Closed by antiboredom** 2015-06-04 14:22 UTC

**Comment by shiffman** [comment] 2015-06-04 15:35
ack, I thought I searched to see if this was reported but clearly I did not!
